### ISSUE TITLE
How to export messages from a channel in a team?

### ISSUE THREAD

**Issue by satrio-yudhoatmojo** [Bannerets/keybase-export#7]
Hi,

Let's say I have a team called "my_family" and there are some channels: #general, #random.  I want to download messages from channel #general.  How do I that using this program?

**Comment by eilvelia** [comment]
Hi, it wasn't intended to use it with big teams, but you can still export a channel using its channel id. The id looks like `0000f0b5c2c2211c8d67ed15e75e656c7862d086e9245420892a7de62cd9ec58`. You can get the id in the chat list by executing `keybase chat api -p -m '{"method": "list"}'`.
It is easy to add support of channel names into `keybase-export`, though.

Config example:

```json
{
  "chats": ["$id$0000f0b5c2c2211c8d67ed15e75e656c7862d086e9245420892a7de62cd9ec58"],
  "init": {
    "type": "initFromRunningService"
  },
  "watcher": {
    "enabled": false,
    "timeout": 20
  },
  "eol": "\n",
  "attachments": {
    "addStub": true
  },
  "elasticsearch": {
    "enabled": false,
    "indexPattern": "keybase_$channelname$",
    "config": {
      "host": "localhost:9200",
      "log": "info"
    }
  },
  "jsonl": {
    "enabled": true,
    "file": "export.jsonl"
  }
}
```

The output will be in the `export.jsonl` file.

(btw use the `update-keybase-bot` branch, since the current master may be broken)

**Comment by satrio-yudhoatmojo** [comment]
Thank you very much! In the config file, is the "elasticsearch" required?  Let's say I just want it to export the chat into jsonl.

**Comment by eilvelia** [comment]
There's `"enabled": false` so the `elasticsearch` field won't be taken into account. IIRC omitting fields is not allowed in the config.

**Comment by eilvelia** [comment]
Since v0.3.0 you can search channels via `my_family#general` strings, e.g:

```json
{
  "chats": ["my_family#general"],
  ...
}
```

Also now you can omit unused fields in the config.
